#pragma checksum "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9138229665879b7b0684ab40ad133bbc2893f0e4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Shedule), @"mvc.1.0.view", @"/Views/Home/Shedule.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Shedule.cshtml", typeof(AspNetCore.Views_Home_Shedule))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\_ViewImports.cshtml"
using IGI_6;

#line default
#line hidden
#line 2 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\_ViewImports.cshtml"
using IGI_6.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"9138229665879b7b0684ab40ad133bbc2893f0e4", @"/Views/Home/Shedule.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"14675d5b518b11293ea926fdd10875a2772f4a9a", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Shedule : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("addForm"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 1 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml"
  
    ViewData["Title"] = "Shedule";

#line default
#line hidden
            BeginContext(43, 294, true);
            WriteLiteral(@"
<h2>Shedule</h2>


<table class=""table"">
    <tr>
        <td>Day</td>
        <td>Time</td>
        <td>Year</td>
        <td>Route name</td>
        <td>BusStop name</td>
    </tr>
    <tbody id=""vals""></tbody>
</table>

<div class=""row"">
    <div class=""col-md-4"">
        ");
            EndContext();
            BeginContext(337, 782, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "6e78b104924040b8b2066f13ffb7da00", async() => {
                BeginContext(356, 301, true);
                WriteLiteral(@"
            <div>Day</div>
            <input name=""Day"" class=""form-control"" />
            <div>Time</div>
            <input name=""Time"" class=""form-control"" />
            <div>Year</div>
            <input name=""Year"" class=""form-control"" />
            <div>RouteName</div>
            ");
                EndContext();
                BeginContext(658, 194, false);
#line 29 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml"
       Write(Html.DropDownList("routeName", new SelectList(new[] { "Name0", "Name1", "Name2", "Name3", "Name4", "Name5", "Name6", "Name7", "Name8", "Name9" }), null, new { @class = "form-control typeName" }));

#line default
#line hidden
                EndContext();
                BeginContext(852, 50, true);
                WriteLiteral("\r\n            <div>BusStopName</div>\r\n            ");
                EndContext();
                BeginContext(903, 199, false);
#line 31 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml"
       Write(Html.DropDownList("busStopName", new SelectList(new[] { "Name0", "Name1", "Name2", "Name3", "Name4", "Name5", "Name6", "Name7", "Name8", "Name9" }), null, new { @class = "form-control busStopName" }));

#line default
#line hidden
                EndContext();
                BeginContext(1102, 10, true);
                WriteLiteral("\r\n        ");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(1119, 107, true);
            WriteLiteral("\r\n        <input type=\"submit\" value=\"Create\" class=\"sendForm btn btn-default\" />\r\n    </div>\r\n</div>\r\n\r\n\r\n");
            EndContext();
            DefineSection("Scripts", async() => {
                BeginContext(1249, 96, true);
                WriteLiteral("\r\n    <script>\r\n        $(document).ready(_ => {\r\n\r\n            $.ajax({\r\n                url: \'");
                EndContext();
                BeginContext(1346, 28, false);
#line 44 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml"
                 Write(Url.Action("shedule", "api"));

#line default
#line hidden
                EndContext();
                BeginContext(1374, 206, true);
                WriteLiteral("\',\r\n                type: \"GET\",\r\n                success: res => loadTable(res)\r\n            })\r\n        });\r\n\r\n       $(document).on(\"click\", \".del\", e => {\r\n\r\n            $.ajax({\r\n                url: \'");
                EndContext();
                BeginContext(1581, 28, false);
#line 53 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml"
                 Write(Url.Action("shedule", "api"));

#line default
#line hidden
                EndContext();
                BeginContext(1609, 736, true);
                WriteLiteral(@"?id=' + e.target.id,
                type: ""DELETE"",
                success: res => loadTable(res)
            });
        });

        $(document).on(""click"", "".sendForm"", e => {

            var shedule = $(""#addForm"").serializeArray().reduce((prev, cur) => {
                if (prev != undefined)
                    prev[cur.name] = cur.value;
                else prev = { [cur.name]: cur.value };

                return prev;

            }, undefined);


            for (let val in shedule) {
                if (shedule[val] == """" || shedule[val] == null) {
                    alert(""Error"");
                    return;
                }
            }

            $.ajax({
                url: '");
                EndContext();
                BeginContext(2346, 30, false);
#line 79 "C:\Users\Lenovo\Desktop\Adam\IGI_6\IGI_6\Views\Home\Shedule.cshtml"
                 Write(Url.Action("addShedule","api"));

#line default
#line hidden
                EndContext();
                BeginContext(2376, 1032, true);
                WriteLiteral(@"',
                type: ""POST"",
                data: {
                    shedule: shedule,
                    routeName: shedule.routeName,
                    busStopName: shedule.busStopName
                },
                success: res => {
                    loadTable(res)
                }
            })

        });

        function loadTable(res) {

            $(""tbody#vals"").html("""");
            for (let i = 0; i < res.length; i++) {
                $(""tbody#vals"").append(`
                            <tr>
                                <td>${res[i].day}</td>
                                <td>${res[i].time}</td>
                                <td>${res[i].year}</td>
                                <td>${res[i].route.name}</td>
                                <td>${res[i].busStop.name}</td>
                                <td class=""del"" id=""${res[i].id}"">x</td>
                            </tr>
                            `);
            }
        }
    </s");
                WriteLiteral("cript>\r\n");
                EndContext();
            }
            );
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
